name: AdvancedFFA
version: '1.0'
main: com.sami.advancedFFA.Main
api-version: '1.21'
authors: [ SAM1_SY ]
depend: [Citizens, DecentHolograms, PlaceholderAPI]
description: A custom FFA plugin.
commands:
  rank:
    description: Manage player ranks
    permission: advancedffa.rank.use
  kit:
    description: Kit editor
  spawn:
    description: Teleports to the spawn.
  guild:
    aliases: [g]